### ISSUE TITLE
clear cache when adding or updating post

### ISSUE THREAD

**Issue by romaque** [cloudpanel-io/clp-wp-varnish-cache#3]
Is it possible to clear the cache when adding a new post or changing?

**Comment by starnetwork** [comment]
Hello,
+1 for this one

if possible, please add this feature to the CLP-WP Varnish plugin

thanks!

**Comment by cloudpanel-io** [comment]
It's already the case.

You can check the PHP controller:

https://www.cloudpanel.io/docs/v2/frontend-area/varnish-cache/developer-guide/php-controller/
